### ISSUE TITLE
[Feature Request] Publish Docker image

### ISSUE THREAD

**Issue by cretz** [temporalio/cli#316]
### Describe the solution you'd like
Need a docker image for this single binary

**Comment by slamdev** [comment]
while waiting for the official image you can use this one: https://github.com/slamdev/temporalite-container-image
```yaml
version: "3.8"
services:
  temporal:
    # https://hub.docker.com/r/slamdev/temporalite/tags
    image: slamdev/temporalite:0.10.7
    restart: on-failure
    command:
      - --namespace=default
      - --db-filename=/tmp/db
    tmpfs:
      - /tmp
    ports:
      - "7233:7233"
      - "8233:8233"
```
ignore `temporalite` name, its temporal cli under the hood, I just re-purposed the repo that was used to build deprecated temporalite.

**Comment by ElanHasson** [comment]
@cretz Can i just send a PR for this?

I was thinking:

Add a GHA workflow to build, test, sign the image and push to ghcr on every release?

**Comment by cretz** [comment]
We are actually in the process of rewriting the innards of the CLI of which #463 is part, yes. We just don't have the publish step yet or the rest of the rewrite completed, stay tuned.

**Comment by ElanHasson** [comment]
Love it thanks!

**Comment by ElanHasson** [comment]
so, `temporalio/admin-tools` has the cli as well :)

**Comment by enricoschaaf** [comment]
Do I see this right that the is no replacement yet for https://github.com/slamdev/temporalite-container-image? Since the PR is merged I assumed it maybe there is but it seems the action just triggers docker builds of other containers that contain the cli but no standalone image.

**Comment by slamdev** [comment]
> Do I see this right that the is no replacement yet for https://github.com/slamdev/temporalite-container-image? Since the PR is merged I assumed it maybe there is but it seems the action just triggers docker builds of other containers that contain the cli but no standalone image.

you can switch to official image now, that's how I use it:
```yaml
  temporal:
    # https://hub.docker.com/r/temporalio/server/tags
    image: temporalio/server:1.21.5.0
    restart: on-failure
    user: "0:0" # running as root to avoid permission issues with writing to /tmp/sqlite/db
    entrypoint:
      - temporal
      - server
      - start-dev
      - --namespace=default
      - --db-filename=/tmp/sqlite/db
      - --ip=0.0.0.0
    tmpfs:
      - /tmp/sqlite
    ports:
      - "7233:7233"
      - "8233:8233"
```
